### ISSUE TITLE
tf version

### ISSUE THREAD

**Issue by euhruska** [hsidky/srv#3]
What tensorflow versions does the code work for? Does it work for 2.0?

**Comment by jpthompson17** [comment]
I seem to have run into this issue, as well. I was getting an import error on `from keras.layers.merge import _Merge` in molgen.py.

As a workaround, I pegged the keras and tf versions in setup.py (and also added a requirement for tensorflow-probability, needed by propagator.py): `install_requires=['numpy', 'scipy', 'scikit-learn', 'tensorflow<=1.15', 'tensorflow-probability<=0.8', 'keras<=2.1.6']`

Are there any plans to support tensorflow 2? I could give this a shot if it would be useful.

**Comment by jpthompson17** [comment]
My previous comment was incorrect. While going through the four well potential notebook, I found I needed keras >=2.2.3, and version 2.3 seems to work fine.
